#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

#################################################################
### GIT
#################################################################

# global gitigore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
ln -s $HOME/.dotfiles/shell/.gitconfig $HOME/.gitconfig
git config --global core.excludesfile $HOME/.global-gitignore
clear

#################################################################
### ZSH
#################################################################

echo 'install oh-my-zhs'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

git clone https://github.com/lukechilds/zsh-nvm ~/.oh-my-zsh/custom/plugins/zsh-nvm
git clone https://github.com/denysdovhan/spaceship-prompt.git ~/.oh-my-zsh/custom/themes/spaceship-prompt
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/zsh-syntax-highlighting

#symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc
ln -s ~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme

#################################################################
### Homebrew
#################################################################

echo 'install homebrew'
echo '----------------'
echo install homebrew
rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'install brew-cask'
echo '-----------------'
brew tap caskroom/cask
brew install brew-cask

#################################################################
### Install colorls https://github.com/athityakumar/colorls#installation
#################################################################
echo 'install colorls for terminal'
echo '-----------------'
gem install colorls

brew tap homebrew/cask-fonts

#################################################################
### PHP
#################################################################

echo 'install php'
echo '------------'
brew install php@7.1
brew install php@7.2
brew install php@7.3

echo 'install xdebug'
echo '--------------'
pecl install xdebug

#################################################################
### Composer
#################################################################

echo 'install composer'
echo '----------------'
cd ~/.dotfiles
brew install composer

#################################################################
### Redis
#################################################################

echo 'install redis'
echo '------------'
brew install redis
brew services start redis

#################################################################
### Valet
#################################################################

echo 'install laravel valet'
echo '---------------------'
composer global require laravel/valet
valet install

curl -o ~/.config/valet/Drivers/JavaScriptSPAValetDriver.php https://gist.githubusercontent.com/jakecobley/366ae401f44f53bbaa65dcd7371050c2/raw/d7a5109f49e66c1589ec2d360869f22dcd6cd4fb/JavaScriptSPAValetDriver.php

#################################################################
### MySQL
#################################################################

echo 'install mysql'
echo '---------------'
brew install mysql
brew services start mysql

#################################################################
### Mongo
#################################################################

echo 'install mongo'
echo '---------------'
brew install mongo
brew services start mongodb

#################################################################
### Images
#################################################################

echo 'install imagemagick'
echo '-------------------'
brew install imagemagick

echo 'install imagick'
echo '---------------'
pecl install imagick

#################################################################
### User Information
#################################################################

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'Instalation was sucessful'

echo '++++++++++++++++++++++++++++++'
echo 'Next Steps'
echo '1. Visit https://nerdfonts.com/ and download your flavor of fonts for colorls'
echo '2. Create .dotfiles-custom/shell/.(exports,aliases,functions,zshrc) for your personal commands'

echo '++++++++++++++++++++++++++++++'
