#!/bin/bash

#install zsh
echo 'install oh-my-zhs'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L http://install.ohmyz.sh | sh

#global gitigore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

#symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

#install composer
echo 'install composer'
echo '----------------'
cd ~/.dotfiles
curl -sS https://getcomposer.org/installer | php
echo 'move composer to /usr/local/bin/composer'
mv -f composer.phar /usr/local/bin/composer

#install homebrew
echo 'install homebrew'
  echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#install wget
echo 'install wget'
echo '------------'
brew install wget --overwrite

#install httpie
echo 'install httpie'
echo '------------'
brew install httpie

#install ack
echo 'install ack'
echo '------------'
brew install ack

#install envoy
echo 'install laravel envoy'
echo '---------------------'
composer global require "laravel/envoy=~1.0"

#install php-cs-fixer
echo 'install php-cs-fixer'
echo '--------------------'
composer global require friendsofphp/php-cs-fixer

#install php
echo 'install php'
echo '------------'
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php
brew install php71
brew install php71-xdebug
sudo brew services start homebrew/php/php71
brew install homebrew/php/php71-mcrypt
brew install homebrew/php/php71-imagick
brew install homebrew/php/php71-mongodb

#install redis
echo 'install redis'
echo '------------'
brew install redis
brew install --HEAD homebrew/php/php71-redis

#install valet
echo 'install laravel valet'
echo '---------------------'
composer global require laravel/valet
valet install

#install mysql
echo 'install mysql'
echo '---------------'
brew install mysql
brew services start mysql

#install mongo
echo 'install mongo'
echo '---------------'
brew install mongo
brew services start mongodb

#install yarn
echo 'install yarn'
echo '------------'
brew install yarn

# dos2unix
echo 'install dos2unix'
echo '------------'
brew install dos2unix

#install file watch (needed for watching phpunit tests)
echo 'install onchange'
echo '----------------'
npm install -g onchange

# install gulp
echo 'install gulp'
echo '------------'
npm install -g gulp

# install bower
echo 'install bower'
echo '------------'
npm install -g bower

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'all done'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. set some sensible os x defaults by running: $HOME/.dotfiles/osx/set-defaults.sh'
echo '2. make a .dotfiles-custom/shell/.aliases for your personal commands'